In [14]:
import pandas as pd
from sqlalchemy import create_engine

In [15]:
csv_file = "brandensfile.csv"
eq_df = pd.read_csv(csv_file)
eq_df.head()

,EarthQ_ID,ID,Date,Time,Latitude,Longitude,Type,Depth,Magnitude,Magnitude Type,Source,Status
0,ISCGEM860706,1,1/2/1965,13:44:18,19.246,145.616,Earthquake,131.6,6.0,MW,ISCGEM,Automatic
1,ISCGEM860737,2,1/4/1965,11:29:49,1.863,127.352,Earthquake,80.0,5.8,MW,ISCGEM,Automatic
2,ISCGEM860762,3,1/5/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,6.2,MW,ISCGEM,Automatic
3,ISCGEM860856,4,1/8/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,5.8,MW,ISCGEM,Automatic
4,ISCGEM860890,5,1/9/1965,13:32:50,11.938,126.427,Earthquake,15.0,5.8,MW,ISCGEM,Automatic

In [16]:
new_eq_df = eq_df[["EarthQ_ID", "ID", "Date", "Time", "Latitude", "Longitude", "Type", "Depth", "Magnitude", "Magnitude Type", "Source", "Status"]].copy()
new_eq_df.head()

,EarthQ_ID,ID,Date,Time,Latitude,Longitude,Type,Depth,Magnitude,Magnitude Type,Source,Status
0,ISCGEM860706,1,1/2/1965,13:44:18,19.246,145.616,Earthquake,131.6,6.0,MW,ISCGEM,Automatic
1,ISCGEM860737,2,1/4/1965,11:29:49,1.863,127.352,Earthquake,80.0,5.8,MW,ISCGEM,Automatic
2,ISCGEM860762,3,1/5/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,6.2,MW,ISCGEM,Automatic
3,ISCGEM860856,4,1/8/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,5.8,MW,ISCGEM,Automatic
4,ISCGEM860890,5,1/9/1965,13:32:50,11.938,126.427,Earthquake,15.0,5.8,MW,ISCGEM,Automatic

In [17]:
rds_connection_string = "<DB USER>:<ENTER DB PASSWORD>@localhost:5432/<ENTER DATABASE NAME>"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [18]:
engine.table_names()

['locations', 'county_zip', 'fema_disaster', 'location', 'earthquake']

In [19]:
new_eq_df = new_eq_df.rename(columns = {
                                  "EarthQ_ID": "earthq_id",
                                   "ID": "id",
                                  "Date": "date", 
                                  "Time":"time", 
                                  "Latitude": "latitude",
                                   "Longitude": "longitude",
                                   "Type":"disaster_type",
                                   "Depth":"depth",
                                   "Magnitude":"magnitude",
                                   "Magnitude Type":"magnitude_type",
                                   "Source":"data_source",
                                   "Status":"status"
                                         })
                                      

new_eq_df.head()

new_eq_df.to_sql(name='earthquake', con=engine, if_exists='append', index=False)