In [25]:
import pandas as pd
from sqlalchemy import create_engine
import os

In [26]:
csv_file = os.path.join("tornadorawdata.csv")
tornadoraw_data_df = pd.read_csv(csv_file)
tornadoraw_data_df

,id,om,data_source,yr,mo,dy,date,time,tz,st,...,len,wid,ns,sn,sg,f1,f2,f3,f4,fc
0,1,1,5,1950,1,3,1/3/1950,11:00:00,3,MO,...,9.50,150,2,0,1,0,0,0,0,0
1,2,2,5,1950,1,3,1/3/1950,11:55:00,3,IL,...,3.60,130,1,1,1,135,0,0,0,0
2,3,3,5,1950,1,3,1/3/1950,16:00:00,3,OH,...,0.10,10,1,1,1,161,0,0,0,0
3,4,4,5,1950,1,13,1/13/1950,5:25:00,3,AR,...,0.60,17,1,1,1,113,0,0,0,0
4,5,5,5,1950,1,25,1/25/1950,19:30:00,3,MO,...,2.30,300,1,1,1,93,0,0,0,0
5,6,6,5,1950,1,25,1/25/1950,21:00:00,3,IL,...,0.10,100,1,1,1,91,0,0,0,0
6,7,7,5,1950,1,26,1/26/1950,18:00:00,3,TX,...,4.70,133,1,1,1,47,0,0,0,0
7,8,8,5,1950,2,11,2/11/1950,13:10:00,3,TX,...,9.90,400,1,1,1,39,0,0,0,0
8,9,9,5,1950,2,11,2/11/1950,13:50:00,3,TX,...,12.00,1000,1,1,1,201,0,0,0,0
9,10,10,5,1950,2,11,2/11/1950,21:00:00,3,TX,...,4.60,100,1,1,1,423,0,0,0,0
10,11,11,5,1950,2,11,2/11/1950,23:55:00,3,TX,...,4.50,67,1,1,1,67,343,0,0,0
11,12,12,5,1950,2,12,2/12/1950,0:30:00,3,TX,...,8.00,833,1,1,1,37,0,0,0,0
12,13,13,5,1950,2,12,2/12/1950,1:15:00,3,TX,...,2.30,233,1,1,1,143,0,0,0,0
13,14,14,5,1950,2,12,2/12/1950,6:10:00,3,TX,...,3.40,100,1,1,1,293,0,0,0,0
14,15,15,5,1950,2,12,2/12/1950,11:57:00,3,TX,...,7.70,100,1,1,1,419,0,0,0,0
15,16,16,5,1950,2,12,2/12/1950,12:00:00,3,MS,...,0.10,10,1,1,1,145,0,0,0,0
16,17,17,5,1950,2,12,2/12/1950,12:00:00,3,MS,...,2.00,10,1,1,1,145,0,0,0,0
17,18,18,5,1950,2,12,2/12/1950,12:00:00,3,TX,...,1.90,50,1,1,1,419,0,0,0,0
18,19,19,5,1950,2,12,2/12/1950,12:30:00,3,AR,...,0.10,100,1,1,1,53,0,0,0,0
19,20,20,5,1950,2,12,2/12/1950,13:00:00,3,LA,...,82.60,100,1,1,1,31,17,15,119,0
20,21,21,5,1950,2,12,2/12/1950,13:20:00,3,LA,...,58.40,100,1,1,1,31,81,17,15,0
21,22,22,5,1950,2,12,2/12/1950,14:00:00,3,LA,...,74.50,100,1,1,1,85,69,81,13,0
22,23,23,5,1950,2,12,2/12/1950,15:00:00,3,AR,...,5.70,100,1,1,1,139,0,0,0,0
23,24,24,5,1950,2,12,2/12/1950,23:00:00,3,LA,...,0.50,33,1,1,1,35,0,0,0,0
24,25,25,5,1950,2,13,2/13/1950,1:00:00,3,TN,...,0.20,10,1,1,1,157,0,0,0,0
25,26,26,5,1950,2,13,2/13/1950,2:00:00,3,TN,...,0.20,10,1,1,1,97,0,0,0,0
26,27,27,5,1950,2,27,2/27/1950,10:20:00,3,OK,...,2.00,50,1,1,1,109,0,0,0,0
27,28,28,5,1950,3,1,3/1/1950,2:30:00,3,MS,...,0.10,10,1,1,1,75,0,0,0,0
28,29,29,5,1950,3,16,3/16/1950,9:15:00,3,FL,...,1.50,150,1,1,1,109,0,0,0,0
29,30,30,5,1950,3,19,3/19/1950,7:30:00,3,LA,...,2.00,33,1,1,1,19,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63615,63616,616995,5,2018,12,1,12/1/2018,19:06:00,3,IL,...,0.21,50,1,1,1,113,0,0,0,0
63616,63617,616996,5,2018,12,1,12/1/2018,19:18:00,3,IL,...,2.44,100,1,1,1,113,0,0,0,0
63617,63618,616997,5,2018,12,1,12/1/2018,19:21:00,3,IL,...,0.12,25,1,1,1,113,0,0,0,0
63618,63619,616998,5,2018,12,1,12/1/2018,19:42:00,3,IL,...,0.49,75,1,1,1,113,0,0,0,0
63619,63620,616999,5,2018,12,2,12/2/2018,1:45:00,3,GA,...,1.48,350,1,1,1,321,0,0,0,0
63620,63621,617000,5,2018,12,2,12/2/2018,1:49:00,3,AL,...,1.03,75,1,1,1,69,0,0,0,0
63621,63622,617001,5,2018,12,2,12/2/2018,8:22:00,3,GA,...,1.86,600,1,1,1,277,0,0,0,0
63622,63623,617002,5,2018,12,2,12/2/2018,13:14:00,3,GA,...,3.20,50,1,1,1,3,0,0,0,0
63623,63624,617003,5,2018,12,2,12/2/2018,13:30:00,3,GA,...,0.19,50,1,1,1,3,0,0,0,0
63624,63625,617004,5,2018,12,2,12/2/2018,13:40:00,3,GA,...,0.59,80,1,1,1,127,0,0,0,0
63625,63626,617005,5,2018,12,2,12/2/2018,14:10:00,3,GA,...,7.09,900,1,1,1,39,0,0,0,0
63626,63627,617006,5,2018,12,2,12/2/2018,17:48:00,3,GA,...,1.40,50,1,1,1,299,0,0,0,0
63627,63628,617007,5,2018,12,3,12/3/2018,1:34:00,3,FL,...,2.15,279,1,1,1,79,0,0,0,0
63628,63629,617008,5,2018,12,9,12/9/2018,7:57:00,3,FL,...,0.12,25,1,1,1,101,0,0,0,0
63629,63630,617009,5,2018,12,9,12/9/2018,10:21:00,3,FL,...,2.76,50,1,1,1,57,0,0,0,0
63630,63631,617010,5,2018,12,9,12/9/2018,10:54:00,3,FL,...,0.13,50,1,1,1,95,0,0,0,0
63631,63632,617011,5,2018,12,18,12/18/2018,15:50:00,3,WA,...,1.35,285,1,1,1,35,0,0,0,0
63632,63633,617012,5,2018,12,20,12/20/2018,7:32:00,3,FL,...,0.19,125,1,1,1,81,0,0,0,0
63633,63634,617013,5,2018,12,20,12/20/2018,7:45:00,3,FL,...,0.76,75,1,1,1,105,0,0,0,0
63634,63635,617014,5,2018,12,20,12/20/2018,8:14:00,3,FL,...,0.07,30,1,1,1,105,0,0,0,0
63635,63636,617015,5,2018,12,20,12/20/2018,11:28:00,3,FL,...,1.02,100,1,1,1,15,0,0,0,0
63636,63637,617016,5,2018,12,20,12/20/2018,16:10:00,3,NC,...,0.33,40,1,1,1,129,0,0,0,0
63637,63638,617017,5,2018,12,26,12/26/2018,15:40:00,3,TX,...,0.34,30,1,1,1,125,0,0,0,0
63638,63639,617018,5,2018,12,26,12/26/2018,16:23:00,3,TX,...,0.57,100,1,1,1,129,0,0,0,0
63639,63640,617019,5,2018,12,27,12/27/2018,6:12:00,3,LA,...,0.32,200,1,1,1,115,0,0,0,0
63640,63641,617020,5,2018,12,27,12/27/2018,10:15:00,3,LA,...,0.60,25,1,1,1,1,0,0,0,0
63641,63642,617021,5,2018,12,27,12/27/2018,10:29:00,3,MS,...,1.29,100,1,1,1,163,0,0,0,0
63642,63643,617022,5,2018,12,31,12/31/2018,12:35:00,3,KY,...,0.76,125,1,1,1,221,0,0,0,0
63643,63644,617023,5,2018,12,31,12/31/2018,13:43:00,3,IN,...,2.01,50,1,1,1,147,0,0,0,0
63644,63645,617024,5,2018,12,31,12/31/2018,14:38:00,3,IN,...,2.20,140,1,1,1,61,0,0,0,0

In [27]:
new_tornadoraw_data_df = tornadoraw_data_df[["id", "om", "data_source","yr", "mo", "dy", "date", "tz", "st", "stf", "stn",
         "mag", "inj", "fat", "loss","closs", "slat", "slon", "elat", "elon", "len", "wid","ns", "sn", "sg", "f1", "f2",
        "f3", "f4", "fc"]].copy()


new_tornadoraw_data_df

,id,om,data_source,yr,mo,dy,date,tz,st,stf,...,len,wid,ns,sn,sg,f1,f2,f3,f4,fc
0,1,1,5,1950,1,3,1/3/1950,3,MO,29,...,9.50,150,2,0,1,0,0,0,0,0
1,2,2,5,1950,1,3,1/3/1950,3,IL,17,...,3.60,130,1,1,1,135,0,0,0,0
2,3,3,5,1950,1,3,1/3/1950,3,OH,39,...,0.10,10,1,1,1,161,0,0,0,0
3,4,4,5,1950,1,13,1/13/1950,3,AR,5,...,0.60,17,1,1,1,113,0,0,0,0
4,5,5,5,1950,1,25,1/25/1950,3,MO,29,...,2.30,300,1,1,1,93,0,0,0,0
5,6,6,5,1950,1,25,1/25/1950,3,IL,17,...,0.10,100,1,1,1,91,0,0,0,0
6,7,7,5,1950,1,26,1/26/1950,3,TX,48,...,4.70,133,1,1,1,47,0,0,0,0
7,8,8,5,1950,2,11,2/11/1950,3,TX,48,...,9.90,400,1,1,1,39,0,0,0,0
8,9,9,5,1950,2,11,2/11/1950,3,TX,48,...,12.00,1000,1,1,1,201,0,0,0,0
9,10,10,5,1950,2,11,2/11/1950,3,TX,48,...,4.60,100,1,1,1,423,0,0,0,0
10,11,11,5,1950,2,11,2/11/1950,3,TX,48,...,4.50,67,1,1,1,67,343,0,0,0
11,12,12,5,1950,2,12,2/12/1950,3,TX,48,...,8.00,833,1,1,1,37,0,0,0,0
12,13,13,5,1950,2,12,2/12/1950,3,TX,48,...,2.30,233,1,1,1,143,0,0,0,0
13,14,14,5,1950,2,12,2/12/1950,3,TX,48,...,3.40,100,1,1,1,293,0,0,0,0
14,15,15,5,1950,2,12,2/12/1950,3,TX,48,...,7.70,100,1,1,1,419,0,0,0,0
15,16,16,5,1950,2,12,2/12/1950,3,MS,28,...,0.10,10,1,1,1,145,0,0,0,0
16,17,17,5,1950,2,12,2/12/1950,3,MS,28,...,2.00,10,1,1,1,145,0,0,0,0
17,18,18,5,1950,2,12,2/12/1950,3,TX,48,...,1.90,50,1,1,1,419,0,0,0,0
18,19,19,5,1950,2,12,2/12/1950,3,AR,5,...,0.10,100,1,1,1,53,0,0,0,0
19,20,20,5,1950,2,12,2/12/1950,3,LA,22,...,82.60,100,1,1,1,31,17,15,119,0
20,21,21,5,1950,2,12,2/12/1950,3,LA,22,...,58.40,100,1,1,1,31,81,17,15,0
21,22,22,5,1950,2,12,2/12/1950,3,LA,22,...,74.50,100,1,1,1,85,69,81,13,0
22,23,23,5,1950,2,12,2/12/1950,3,AR,5,...,5.70,100,1,1,1,139,0,0,0,0
23,24,24,5,1950,2,12,2/12/1950,3,LA,22,...,0.50,33,1,1,1,35,0,0,0,0
24,25,25,5,1950,2,13,2/13/1950,3,TN,47,...,0.20,10,1,1,1,157,0,0,0,0
25,26,26,5,1950,2,13,2/13/1950,3,TN,47,...,0.20,10,1,1,1,97,0,0,0,0
26,27,27,5,1950,2,27,2/27/1950,3,OK,40,...,2.00,50,1,1,1,109,0,0,0,0
27,28,28,5,1950,3,1,3/1/1950,3,MS,28,...,0.10,10,1,1,1,75,0,0,0,0
28,29,29,5,1950,3,16,3/16/1950,3,FL,12,...,1.50,150,1,1,1,109,0,0,0,0
29,30,30,5,1950,3,19,3/19/1950,3,LA,22,...,2.00,33,1,1,1,19,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63615,63616,616995,5,2018,12,1,12/1/2018,3,IL,17,...,0.21,50,1,1,1,113,0,0,0,0
63616,63617,616996,5,2018,12,1,12/1/2018,3,IL,17,...,2.44,100,1,1,1,113,0,0,0,0
63617,63618,616997,5,2018,12,1,12/1/2018,3,IL,17,...,0.12,25,1,1,1,113,0,0,0,0
63618,63619,616998,5,2018,12,1,12/1/2018,3,IL,17,...,0.49,75,1,1,1,113,0,0,0,0
63619,63620,616999,5,2018,12,2,12/2/2018,3,GA,13,...,1.48,350,1,1,1,321,0,0,0,0
63620,63621,617000,5,2018,12,2,12/2/2018,3,AL,1,...,1.03,75,1,1,1,69,0,0,0,0
63621,63622,617001,5,2018,12,2,12/2/2018,3,GA,13,...,1.86,600,1,1,1,277,0,0,0,0
63622,63623,617002,5,2018,12,2,12/2/2018,3,GA,13,...,3.20,50,1,1,1,3,0,0,0,0
63623,63624,617003,5,2018,12,2,12/2/2018,3,GA,13,...,0.19,50,1,1,1,3,0,0,0,0
63624,63625,617004,5,2018,12,2,12/2/2018,3,GA,13,...,0.59,80,1,1,1,127,0,0,0,0
63625,63626,617005,5,2018,12,2,12/2/2018,3,GA,13,...,7.09,900,1,1,1,39,0,0,0,0
63626,63627,617006,5,2018,12,2,12/2/2018,3,GA,13,...,1.40,50,1,1,1,299,0,0,0,0
63627,63628,617007,5,2018,12,3,12/3/2018,3,FL,12,...,2.15,279,1,1,1,79,0,0,0,0
63628,63629,617008,5,2018,12,9,12/9/2018,3,FL,12,...,0.12,25,1,1,1,101,0,0,0,0
63629,63630,617009,5,2018,12,9,12/9/2018,3,FL,12,...,2.76,50,1,1,1,57,0,0,0,0
63630,63631,617010,5,2018,12,9,12/9/2018,3,FL,12,...,0.13,50,1,1,1,95,0,0,0,0
63631,63632,617011,5,2018,12,18,12/18/2018,3,WA,53,...,1.35,285,1,1,1,35,0,0,0,0
63632,63633,617012,5,2018,12,20,12/20/2018,3,FL,12,...,0.19,125,1,1,1,81,0,0,0,0
63633,63634,617013,5,2018,12,20,12/20/2018,3,FL,12,...,0.76,75,1,1,1,105,0,0,0,0
63634,63635,617014,5,2018,12,20,12/20/2018,3,FL,12,...,0.07,30,1,1,1,105,0,0,0,0
63635,63636,617015,5,2018,12,20,12/20/2018,3,FL,12,...,1.02,100,1,1,1,15,0,0,0,0
63636,63637,617016,5,2018,12,20,12/20/2018,3,NC,37,...,0.33,40,1,1,1,129,0,0,0,0
63637,63638,617017,5,2018,12,26,12/26/2018,3,TX,48,...,0.34,30,1,1,1,125,0,0,0,0
63638,63639,617018,5,2018,12,26,12/26/2018,3,TX,48,...,0.57,100,1,1,1,129,0,0,0,0
63639,63640,617019,5,2018,12,27,12/27/2018,3,LA,22,...,0.32,200,1,1,1,115,0,0,0,0
63640,63641,617020,5,2018,12,27,12/27/2018,3,LA,22,...,0.60,25,1,1,1,1,0,0,0,0
63641,63642,617021,5,2018,12,27,12/27/2018,3,MS,28,...,1.29,100,1,1,1,163,0,0,0,0
63642,63643,617022,5,2018,12,31,12/31/2018,3,KY,21,...,0.76,125,1,1,1,221,0,0,0,0
63643,63644,617023,5,2018,12,31,12/31/2018,3,IN,18,...,2.01,50,1,1,1,147,0,0,0,0
63644,63645,617024,5,2018,12,31,12/31/2018,3,IN,18,...,2.20,140,1,1,1,61,0,0,0,0

In [28]:
rds_connection_string = "postgres:Dbadmin@localhost:5432/NaturalDisaster_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [29]:
engine.table_names()

['county_zip', 'fema_disaster', 'locations', 'tornado', 'earthquake']

In [30]:
new_tornadoraw_data_df = new_tornadoraw_data_df.rename(columns = {"id": "id","om":  "om", "data_source": "data_source",
            "yr": "yr","mo": "mo", "dy": "dy",  "date": "date", "time":"time", "tz": "tz", "st": "states",
             "stf":"stf", "stn":"stn", "mag":"magnitude", "inj":"inj", "fat":"fat", "loss": "loss", "closs":"closs",
             "slat": "start_lat", "slon": "start_lon", "elat": "end_lat", "elon": "end_lon", "len":"len",
            "wid":"wid", "ns":"ns", "sn":"sn", "sg":"sg", "f1":"f1", "f2":"f2", "f3":"f3",  "f4":"f4", "fc":"fc"  })
                                      

new_tornadoraw_data_df.head()

,id,om,data_source,yr,mo,dy,date,tz,states,stf,...,len,wid,ns,sn,sg,f1,f2,f3,f4,fc
0,1,1,5,1950,1,3,1/3/1950,3,MO,29,...,9.5,150,2,0,1,0,0,0,0,0
1,2,2,5,1950,1,3,1/3/1950,3,IL,17,...,3.6,130,1,1,1,135,0,0,0,0
2,3,3,5,1950,1,3,1/3/1950,3,OH,39,...,0.1,10,1,1,1,161,0,0,0,0
3,4,4,5,1950,1,13,1/13/1950,3,AR,5,...,0.6,17,1,1,1,113,0,0,0,0
4,5,5,5,1950,1,25,1/25/1950,3,MO,29,...,2.3,300,1,1,1,93,0,0,0,0

In [31]:
new_tornadoraw_data_df.to_sql(name='tornado', con=engine, if_exists='append', index=False)